"""
WebSocket Message Models for Agent Server

Defines the message protocol for client-server communication.
"""

from enum import Enum
from typing import Any, Literal, Optional
from pydantic import BaseModel, Field


# =============================================================================
# Enums
# =============================================================================


class ClientMessageType(str, Enum):
    """Types of messages the client can send."""

    CHAT_REQUEST = "chat_request"
    CHAT_RESUME = "chat_resume"
    CANCEL = "cancel"


class ServerMessageType(str, Enum):
    """Types of messages the server can send."""

    CONNECTION_ACK = "connection_ack"
    TOKEN = "token"
    STATUS = "status"
    TOOL_START = "tool_start"
    TOOL_RESULT = "tool_result"
    LOCATION_CONFIRMATION = "location_confirmation"
    COMPLETE = "complete"
    ERROR = "error"


class AgentStage(str, Enum):
    """Stages of agent processing."""

    PLANNING = "planning"
    TOOL_CALL = "tool_call"
    ANALYZING = "analyzing"


# =============================================================================
# Shared Models
# =============================================================================


class ChatMessage(BaseModel):
    """A single chat message in history."""

    role: str = Field(..., description="Message role: 'user' or 'assistant'")
    content: str = Field(..., description="Message content")


class Coordinates(BaseModel):
    """Geographic coordinates."""

    lat: float = Field(..., description="Latitude")
    lon: float = Field(..., description="Longitude")


OSMType = Literal["relation", "way", "node"]
# mapper from OSMType to its first letter capitalized
OSMPrefixType = Literal["R", "W", "N"]
OSMTypeMapper = {
    "relation": "R",
    "way": "W",
    "node": "N",
}


def get_osm_type_prefix(osm_type: OSMType) -> str:
    return OSMTypeMapper.get(osm_type, "")


class LocationOption(BaseModel):
    """A location option for disambiguation."""

    name: str = Field(..., description="Location display name")
    coordinates: list[float] = Field(..., description="[lat, lon] coordinates")
    place_id: Optional[int] = Field(default=None, description="Place ID")
    osm_id: Optional[int] = Field(default=None, description="OSM ID")
    osm_type: Optional[OSMType] = Field(default=None, description="OSM type")
    osm_type_prefix: Optional[OSMPrefixType] = Field(
        default=None, description="OSM type prefix"
    )


class Artifacts(BaseModel):
    """Artifacts generated by the agent (maps, images, etc.)."""

    maps: list[str | dict[str, Any]] = Field(
        default_factory=list, description="Map data (base64, URLs, or pydeck specs)"
    )
    thumbnails: list[str] = Field(default_factory=list, description="Thumbnail images")
    urls: list[str] = Field(default_factory=list, description="External URLs")


# =============================================================================
# Client -> Server Messages
# =============================================================================


class ChatRequestMessage(BaseModel):
    """Client request to start a new chat."""

    type: str = Field(default=ClientMessageType.CHAT_REQUEST.value)
    message: str = Field(..., description="User message")
    chat_history: list[ChatMessage] = Field(
        default_factory=list, description="Previous conversation history"
    )
    confirmed_locations: dict[str, list[float]] = Field(
        default_factory=dict,
        description="Cache of confirmed locations: {name: [lat, lon]}",
    )
    document_context: Optional[str] = Field(
        default=None, description="Extracted text from uploaded documents"
    )
    language: Optional[str] = Field(
        default=None,
        description="User's language for translation (auto-detected if None)",
    )


class ChatResumeMessage(BaseModel):
    """Client request to resume after location confirmation."""

    type: str = Field(default=ClientMessageType.CHAT_RESUME.value)
    confirmed_location: LocationOption = Field(
        ..., description="The location the user confirmed"
    )
    pause_state: dict[str, Any] = Field(
        ..., description="Serialized agent state from location_confirmation message"
    )


class CancelMessage(BaseModel):
    """Client request to cancel current operation."""

    type: str = Field(default=ClientMessageType.CANCEL.value)


# =============================================================================
# Server -> Client Messages
# =============================================================================


class ConnectionAckMessage(BaseModel):
    """Server acknowledgment of WebSocket connection."""

    type: str = Field(default=ServerMessageType.CONNECTION_ACK.value)
    server_version: str = Field(..., description="Agent server version")


class TokenMessage(BaseModel):
    """Streaming token from LLM response."""

    type: str = Field(default=ServerMessageType.TOKEN.value)
    content: str = Field(..., description="Token text content")


class StatusMessage(BaseModel):
    """Agent status update."""

    type: str = Field(default=ServerMessageType.STATUS.value)
    stage: AgentStage = Field(..., description="Current processing stage")
    detail: Optional[str] = Field(default=None, description="Additional detail")


class ToolStartMessage(BaseModel):
    """Notification that a tool is being executed."""

    type: str = Field(default=ServerMessageType.TOOL_START.value)
    tool_name: str = Field(..., description="Name of the tool being called")
    tool_input: dict[str, Any] = Field(..., description="Tool input parameters")


class ToolResultMessage(BaseModel):
    """Result from tool execution."""

    type: str = Field(default=ServerMessageType.TOOL_RESULT.value)
    tool_name: str = Field(..., description="Name of the tool that was called")
    result: dict[str, Any] = Field(..., description="Tool result data")
    artifacts: Artifacts = Field(
        default_factory=Artifacts, description="Artifacts generated by the tool"
    )


class LocationConfirmationMessage(BaseModel):
    """Request for user to confirm ambiguous location."""

    type: str = Field(default=ServerMessageType.LOCATION_CONFIRMATION.value)
    options: list[LocationOption] = Field(
        ..., description="Location options for user to choose from"
    )
    pause_state: dict[str, Any] = Field(
        ..., description="Serialized agent state to resume after confirmation"
    )


class CompleteMessage(BaseModel):
    """Final response indicating completion."""

    type: str = Field(default=ServerMessageType.COMPLETE.value)
    response: str = Field(..., description="Final response text")
    artifacts: Artifacts = Field(
        default_factory=Artifacts, description="All artifacts from the response"
    )
    error: bool = Field(default=False, description="Whether an error occurred")


class ErrorMessage(BaseModel):
    """Error message."""

    type: str = Field(default=ServerMessageType.ERROR.value)
    message: str = Field(..., description="Error description")
    recoverable: bool = Field(default=True, description="Whether the client can retry")


# =============================================================================
# Union Types for Parsing
# =============================================================================

# Type alias for any server message
ServerMessage = (
    ConnectionAckMessage
    | TokenMessage
    | StatusMessage
    | ToolStartMessage
    | ToolResultMessage
    | LocationConfirmationMessage
    | CompleteMessage
    | ErrorMessage
)

# Type alias for any client message
ClientMessage = ChatRequestMessage | ChatResumeMessage | CancelMessage
